### ISSUE TITLE
Improve look & feel for pucks

### ISSUE THREAD

**Issue by ignaciosegura** [ignaciosegura/bouncerback#19]
Puck is just a rectangle right now.

**Tasks:**

- [ ] Puck should be and arc
- [ ] Detection arc and renered arc should be exactly the same.
- [ ] add bounce FX using box-shadow, if possible.
